version: "3.9"
services:
    # Uncomment to use redis
    # redis:
    #   image: redis:7-alpine
    #   ports:
    #     - 6379:6379
    postgres:
        container_name: postgres
        image: postgres:12.12
        restart: always
        environment:
            - POSTGRES_USER=milon27
            - POSTGRES_PASSWORD=myPassWord
            - POSTGRES_DB=my_db
        ports:
            - 5432:5432
        volumes:
            - db_vol:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=pg@g.com
            - PGADMIN_DEFAULT_PASSWORD=1234
        ports:
            - 5050:80
    # after login into pgadmin to create a db server: use postgres as host, user: milon27 , password: myPassWord
    #volumes(root label)
volumes:
    db_vol: {}
